import Link from 'next/link';
import type { CSSProperties } from 'react';
import Header from '../components/Header';
import ContactForm from '../components/ContactForm';
import ProjectGallery from '../components/ProjectGallery';
import { getContent } from '../lib/content';
import { classifyProject } from '../lib/project-type';
import { siteAsset, siteSrcSet } from '../lib/site-path';
export const dynamic = 'force-dynamic';
const str=(x:any)=>typeof x==='string'?x:'';
const arr=(x:any)=>Array.isArray(x)?x:[];
const visible=(x:any)=>x?.visible!==false;
const dateRange=(x:any)=>`${x.startDate||''}${x.startDate&&x.endDate?' — ':''}${x.current?'Present':(x.endDate||'')}`;
export default function Home(){
  const c=getContent(), profile=c.profile as any, contact=c.contact as any, site=c.site as any;
  const useCutout=['/images/fozayel-760.webp','/images/fozayel-1200.webp'].includes(String(profile.image||''));
  const heroPortrait=useCutout?'/images/fozayel-cutout.webp':(str(profile.image)||'/images/fozayel-cutout.webp');
  const experience=arr(c.experience).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const projects=arr(c.projects).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const projectCards=projects.map((p:any)=>({id:p.id,slug:p.slug,name:p.name,shortDescription:p.shortDescription||p.blurb||p.description||'',description:p.description||'',category:p.category||p.stack||'',stack:p.stack||'',technologies:arr(p.technologies),featured:!!p.featured,featuredImage:p.featuredImage||'',liveUrl:p.liveUrl||'',order:p.order||0,repoUpdatedAt:p.repoUpdatedAt||'',projectType:classifyProject(p)}));
  const skills=arr(c.skills).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const education=arr(c.education).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const services=arr(c.services).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const testimonials=arr(c.testimonials).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const awards=arr(c.awards).filter(visible).sort((a:any,b:any)=>(a.order||0)-(b.order||0));
  const paragraphs=arr(profile.biography); const groups=[...new Set(skills.map((x:any)=>x.category||'Other'))];
  let sectionCounter=5;const servicesNumber=services.length?String(sectionCounter++).padStart(2,'0'):'';const awardsNumber=awards.length?String(sectionCounter++).padStart(2,'0'):'';const educationNumber=education.length?String(sectionCounter++).padStart(2,'0'):'';const testimonialsNumber=testimonials.length?String(sectionCounter++).padStart(2,'0'):'';const contactNumber=String(sectionCounter).padStart(2,'0');
  const years=Math.max(1,new Date().getFullYear()-2022);
  const personJson={"@context":"https://schema.org","@type":"Person",name:profile.name,url:process.env.NEXT_PUBLIC_SITE_URL||site.canonicalUrl,image:profile.image,jobTitle:profile.title,email:contact.email,address:{"@type":"PostalAddress",addressLocality:'Dhaka',addressCountry:'BD'},sameAs:arr(profile.socialLinks).map((x:any)=>x.url).filter((x:string)=>x.startsWith('http'))};
  const themeStyle={'--theme-light':site.theme?.light||'#fdfdfc','--theme-dark':site.theme?.dark||'#141414','--accent-light':site.theme?.accent||'#22c55e','--accent-dark':site.theme?.darkAccent||'#36d978'} as CSSProperties;
  return <div className="site-shell" style={themeStyle}>
    <a className="skip-link" href="#main">Skip to content</a>
    <Header labels={site.navLabels} logo={site.logo||'F.'} name={profile.name} location={String(profile.location||'Dhaka').split(',')[0]} availability={profile.availability||'Available for new projects'} projectCount={projects.length} skillCount={skills.length}/>
    <main id="main">
      <section className="hero section-container" id="top" aria-labelledby="hero-title">
        <div className="hero-title-wrap"><p className="hero-greeting">Hi, I’m</p><h1 id="hero-title"><span className="hero-outline">FOZAYEL  IBN</span><span className="hero-solid"> AYAZ</span></h1></div>
        <div className="hero-portrait-layer"><picture className="hero-picture">{useCutout&&<source srcSet={siteSrcSet('/images/fozayel-cutout-520.webp 520w, /images/fozayel-cutout-760.webp 760w, /images/fozayel-cutout-1024.webp 1024w, /images/fozayel-cutout.webp 1254w')} sizes="(max-width: 720px) 130vw, (max-width: 1300px) 58vw, 760px" type="image/webp"/>}<img className="hero-portrait" src={siteAsset(useCutout?'/images/fozayel-cutout.png':heroPortrait)} alt={profile.imageAlt||'Portrait of Fozayel Ibn Ayaz'} width="1254" height="1254" tabIndex={0} fetchPriority="high" decoding="async"/></picture></div>
        <div className="hero-copy">
          <h2>{str(profile.title).split(' · ')[0]} <span>&amp; Data Analyst</span></h2>
          <p>{str(profile.shortIntroduction)}</p>
          <a className="hero-project-cta" href="#projects">View Projects <span aria-hidden="true">↗</span></a>
        </div>
        <nav className="hero-socials" aria-label="Contact and social links">
          {arr(profile.socialLinks).map((social:any)=>{const label=String(social.label||'');const kind=label.toLowerCase().includes('git')?'github':label.toLowerCase().includes('email')?'mail':label.toLowerCase().includes('phone')?'phone':'link';return <a key={label} href={social.url} target={social.url?.startsWith('http')?'_blank':undefined} rel={social.url?.startsWith('http')?'noreferrer':undefined}><ContactGlyph kind={kind}/>{label}</a>})}
          <a href={`https://maps.google.com/?q=${encodeURIComponent(str(profile.location||'Dhaka, Bangladesh'))}`} target="_blank" rel="noreferrer"><ContactGlyph kind="location"/>Location</a>
        </nav>
        <a href="#about" className="scroll-cue"><span className="scroll-mouse"><i/></span><span>SCROLL</span><span className="scroll-mouse"><i/></span></a>
      </section>
      <div className="ticker" aria-label="Areas of focus"><div className="ticker-track">{[0,1].map(n=><span key={n} className="ticker-set">{['FULL-STACK DEVELOPMENT','DATA & ANALYTICS','WORDPRESS ENGINEERING','PERFORMANCE & SEO','SYSTEMS THAT SHIP'].map((x,i)=><span key={x+n} className="ticker-item">{x}<i>✳</i></span>)}</span>)}</div></div>
      <section className="section-container section-block" id="about">
        <SectionHead number="01" kicker={c.about.kicker} title="/ ABOUT" right="A little context before the code."/>
        <div className="about-grid"><div className="about-heading"><p className="section-title">{c.about.title}</p><div className="about-stamp"><span>BASED IN</span><strong>DHAKA, BD</strong><small>GMT +6 · 23.8103° N</small></div></div><div className="about-copy">{paragraphs.map((p:any,i)=><p key={i}>{str(p)}</p>)}<div className="facts-grid">{arr(c.about.facts).map((f:any)=><div className="fact" key={f.k}><span>{f.k}</span><strong>{f.v}</strong></div>)}</div></div></div>
      </section>
      {projects.length>0&&<section className="section-container section-block work-section" id="projects">
        <SectionHead number="02" kicker="Selected work" title="/ THINGS I’VE BUILT" right={`${projects.length.toString().padStart(2,'0')} projects`}/>
        <div className="section-intro"><p className="section-title">Small details. Real-world work.</p><p>Selected work spanning product development, analytics, e-commerce and content systems.</p></div>
        <ProjectGallery projects={projectCards}/>
      </section>}
      <section className="section-container section-block experience-section" id="experience">
        <SectionHead number="03" kicker="Experience" title="/ WHERE I’VE WORKED" right={`${experience.length.toString().padStart(2,'0')} professional chapters`}/>
        <div className="section-intro"><p className="section-title">Good work is a team sport.</p><p>Roles across development, analytics, IT operations and teaching.</p></div>
        <div className="timeline">{experience.map((role:any,i:number)=><article className="timeline-row" key={role.id||`${role.company}-${i}`}><div className="timeline-number">0{i+1}<span/></div><div className="timeline-main"><div className="timeline-title"><div className="role-copy">{role.logo&&<img className="role-logo" src={siteAsset(role.logo)} alt="" loading="lazy"/>}<div><h3>{role.title}<span className="title-dot"> · </span>{role.companyUrl?<a className="company-link" href={role.companyUrl} target="_blank" rel="noreferrer">{role.company}</a>:<span>{role.company}</span>}</h3><p>{role.description}</p></div></div><span className="timeline-date">{dateRange(role)}</span></div><ul className="responsibility-list">{arr(role.responsibilities).map((b:any,j:number)=><li key={j}>{b}</li>)}</ul><div className="tag-list">{arr(role.technologies).map((tag:any)=><span className="tag" key={tag}>{tag}</span>)}</div></div></article>)}</div>
      </section>
      <section className="section-container section-block skills-section" id="skills">
        <SectionHead number="04" kicker="Toolbox" title="/ TECHNOLOGIES I USE" right={`${skills.length.toString().padStart(2,'0')} skills & disciplines`}/>
        <div className="section-intro"><p className="section-title">A flexible toolkit for<br/>getting the work done.</p><p>From the first interface to the analytics and infrastructure behind it.</p></div>
        <div className="skill-groups">{groups.map((g:any,i:number)=><div className="skill-group" key={g}><div className="skill-group-top"><span>0{i+1} / CATEGORY</span><span className="skill-cross">↗</span></div><h3>{g}</h3><div className="tag-list">{skills.filter((x:any)=>(x.category||'Other')===g).map((s:any)=><span className="tag skill-tag" key={s.id||s.name}>{s.icon&&s.icon.startsWith('/')?<img src={siteAsset(s.icon)} alt="" loading="lazy"/>:s.icon&&<i>{s.icon}</i>}{s.name}{s.experience&&<small>{s.experience}</small>}</span>)}</div></div>)}</div>
      </section>
      {services.length>0&&<section className="section-container section-block" id="services"><SectionHead number={servicesNumber} kicker="Services" title="/ WHAT I CAN HELP WITH" right={`${services.length.toString().padStart(2,'0')} offerings`}/><div className="section-intro"><p className="section-title">Practical solutions,<br/>built around the need.</p><p>Services and capabilities. Tell me the goal; we can work out the right scope together.</p></div><div className="services-grid">{services.map((service:any,i:number)=><article className="service-card" key={service.id||i}><div className="service-mark">{service.icon||`0${i+1}`}</div><h3>{service.title}</h3><p>{service.description}</p>{arr(service.features).length>0&&<ul>{arr(service.features).map((feature:any,j:number)=><li key={j}>{feature}</li>)}</ul>}</article>)}</div></section>}
      {awards.length>0&&<section className="section-container section-block" id="awards"><SectionHead number={awardsNumber} kicker="Recognition" title="/ AWARDS & CREDENTIALS" right={`${awards.length.toString().padStart(2,'0')} entries`}/><div className="education-list">{awards.map((award:any,i:number)=><article className="education-row" key={award.id||i}><span className="education-count">{award.date||`0${i+1}`}</span><div><h3>{award.title}</h3><p>{award.issuer}{award.description?` · ${award.description}`:''}</p></div>{award.url&&<a className="education-dates" href={award.url} target="_blank" rel="noreferrer">View ↗</a>}</article>)}</div></section>}
      {education.length>0&&<section className="section-container section-block education-section" id="education">
        <SectionHead number={educationNumber} kicker="Education" title="/ ACADEMIC BACKGROUND" right="A foundation for lifelong learning"/>
        <div className="education-list">{education.map((e:any,i:number)=><article className="education-row" key={e.id||i}><span className="education-count">0{i+1}</span><div><h3>{e.logo&&<img className="education-logo" src={siteAsset(e.logo)} alt="" loading="lazy"/>}{e.degree}</h3><p>{e.url?<a href={e.url} target="_blank" rel="noreferrer">{e.institution}</a>:e.institution}{e.field&&e.field!==e.degree?` · ${e.field}`:''}</p></div><span className="education-dates">{e.startDate}{e.startDate&&e.endDate?' — ':''}{e.endDate}</span></article>)}</div>
      </section>}
      {testimonials.length>0&&<section className="section-container section-block" id="testimonials"><SectionHead number={testimonialsNumber} kicker="Feedback" title="/ KIND WORDS" right={`${testimonials.length.toString().padStart(2,'0')} notes`}/><div className="section-intro"><p className="section-title">Thoughts from<br/>people I’ve worked with.</p><p>Feedback shared by collaborators and clients.</p></div><div className="testimonial-grid">{testimonials.map((t:any,i:number)=><blockquote className="testimonial-card" key={t.id||i}><span className="quote-mark">“</span><p>{t.testimonial}</p><footer>{t.photo&&<img src={siteAsset(t.photo)} alt="" width="38" height="38"/>}<div><strong>{t.name}</strong><small>{[t.position,t.company].filter(Boolean).join(' · ')}</small></div>{t.url&&<a href={t.url} target="_blank" rel="noreferrer" aria-label={`View ${t.name} profile`}>↗</a>}</footer></blockquote>)}</div></section>}
      <section className="contact-section" id="contact"><div className="section-container contact-inner"><SectionHead number={contactNumber} kicker="Say hello" title="/ NEXT STEP" right={contact.location||profile.location}/><div className="contact-layout"><div className="contact-copy"><p className="contact-title">{contact.ctaTitle}</p><p className="contact-sub">{contact.ctaText}</p><div className="contact-links"><a href={`mailto:${contact.email}`}><span>EMAIL</span>{contact.email}<b>↗</b></a><a href={`tel:${contact.phone}`}><span>PHONE</span>{contact.phone}<b>↗</b></a>{arr(contact.socialProfiles).map((s:any)=><a key={s.label} href={s.url} target={s.url?.startsWith('http')?'_blank':undefined} rel={s.url?.startsWith('http')?'noreferrer':undefined}><span>{String(s.label||'SOCIAL').toUpperCase()}</span>{String(s.url||'').replace(/^https?:\/\//,'')}<b>↗</b></a>)}</div></div>{contact.formSettings?.enabled!==false?<ContactForm email={contact.email} provider={contact.formSettings?.provider||'mailto'} endpoint={contact.formSettings?.endpoint||''}/>:<div className="contact-form-disabled"><span className="section-kicker">FORM TEMPORARILY OFF</span><p>Please reach out directly using the contact details.</p><a className="button button-primary" href={`mailto:${contact.email}`}>Email me <span>↗</span></a></div>}</div><footer className="site-footer"><a className="footer-brand" href="#top" aria-label="F. — back to top">{String(site.logo||'F.').startsWith('/')?<img src={siteAsset(site.logo)} alt=""/>:site.logo==='F.'?<>F<span>.</span></>:site.logo}</a><span>{site.footer}</span><span>{site.copyright}</span><a href={siteAsset('/admin')} className="admin-link">{process.env.NEXT_PUBLIC_GITHUB_PAGES==='true'?'Edit content':'CMS'} ↗</a></footer></div></section>
    </main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(personJson)}}/>
  </div>;
}
function ContactGlyph({kind}:{kind:string}){const common={viewBox:'0 0 24 24',width:14,height:14,fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,focusable:'false' as const, 'aria-hidden':true};if(kind==='mail')return <svg {...common}><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/></svg>;if(kind==='phone')return <svg {...common}><path d="M7 3h3l2 5-2 2a15 15 0 0 0 4 4l2-2 5 2v3c0 1.1-.9 2-2 2C10.8 19 5 13.2 5 6c0-1.7.8-3 2-3Z"/></svg>;if(kind==='location')return <svg {...common}><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>;if(kind==='github')return <svg {...common}><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/></svg>;return <svg {...common}><path d="M14 3h7v7m0-7L10 14"/><path d="M19 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7a2 2 0 0 1 2-2h6"/></svg>}
function SectionHead({number,kicker,title,right}:{number:string;kicker:string;title:string;right:string}){return <div className="section-head"><div className="section-head-left"><span className="section-number">{number}</span><span className="section-kicker">{kicker}</span><h2>{title}</h2></div><span className="section-head-note">{right}</span></div>}
